[package]
name = "xilem_understory_scroll"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
masonry = { git = "https://github.com/linebender/xilem.git", rev = "bf81712d44e314cd357c48c3586588179492c8b0", version = "0.4.0" }
masonry_winit = { git = "https://github.com/linebender/xilem.git", rev = "bf81712d44e314cd357c48c3586588179492c8b0", version = "0.4.0" }
tracing = "0.1.44"
understory_virtual_list = { git = "https://github.com/endoli/understory.git", rev = "d534c174d6d74e0d7f143b3e468b888851586fdb", version = "0.1.0" }
xilem = { git = "https://github.com/linebender/xilem.git", rev = "bf81712d44e314cd357c48c3586588179492c8b0", version = "0.4.0" }

[dev-dependencies]
color = "0.3.2"
masonry = { git = "https://github.com/linebender/xilem.git", rev = "bf81712d44e314cd357c48c3586588179492c8b0", version = "0.4.0", features = [
  "testing"
] }
